// components/halls/sovereign-stream.tsx
"use client";

import React, { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  MessageSquare,
  FileText,
  ShieldAlert,
  Landmark,
  Search,
  Send,
  ChevronDown,
  ChevronUp,
  Clock,
  Hash,
  Vote,
  CheckCircle2,
  XCircle,
  Lock,
  Reply,
  MoreHorizontal,
  Filter,
  Pin,
  Calendar,
  TrendingUp,
  Wrench,
  BadgeCheck,
  X,
} from "lucide-react";
import { cn } from "@/lib/utils";

//  Types

export type StreamPostType = "proposal" | "report" | "appeal" | "ledger_update";

export interface StreamReply {
  id: string;
  ledgerId: string;
  displayName?: string;
  avatar?: string;
  content: string;
  createdAt: Date;
  isExecutive?: boolean;
  executiveRole?: string;
}

export interface StreamPost {
  id: string;
  type: StreamPostType;
  title: string;
  content: string;
  ledgerId: string;
  displayName?: string;
  avatar?: string;
  createdAt: Date;
  voteClosesAt?: Date;
  voteYes?: number;
  voteNo?: number;
  voteAbstain?: number;
  status?: "active" | "passed" | "rejected" | "executing" | "completed";
  amount?: number;
  isPinned?: boolean;
  isRead?: boolean;
  replies: StreamReply[];
  tags?: string[];
}

export interface SovereignStreamProps {
  hallId: string;
  hallName: string;
  posts: StreamPost[];
  currentUserLedgerId: string;
  isSpeaker?: boolean;
  isTreasurer?: boolean;
  isWarden?: boolean;
  isScribe?: boolean;
  isAdmin?: boolean;
  onCreatePost?: (
    post: Omit<StreamPost, "id" | "createdAt" | "replies">,
  ) => Promise<void>;
  onReply?: (postId: string, content: string) => Promise<void>;
  onVote?: (postId: string, vote: "yes" | "no" | "abstain") => Promise<void>;
  onPin?: (postId: string) => Promise<void>;
  className?: string;
}

//  Role Config

const TYPE_CONFIG: Record<
  StreamPostType,
  {
    label: string;
    prefix: string;
    icon: React.ElementType;
    color: string;
    bg: string;
    border: string;
    badge: string;
    description: string;
  }
> = {
  proposal: {
    label: "Proposal",
    prefix: "[PROPOSAL]",
    icon: Vote,
    color: "text-amber-400",
    bg: "bg-amber-500/8",
    border: "border-amber-500/20",
    badge: "bg-amber-500/15 text-amber-400 border-amber-500/20",
    description: "Requires hall vote. Capital-weighted.",
  },
  report: {
    label: "Report",
    prefix: "[REPORT]",
    icon: FileText,
    color: "text-emerald-400",
    bg: "bg-emerald-500/8",
    border: "border-emerald-500/20",
    badge: "bg-emerald-500/15 text-emerald-400 border-emerald-500/20",
    description: "Treasurer reports. No vote required.",
  },
  appeal: {
    label: "Appeal",
    prefix: "[APPEAL]",
    icon: ShieldAlert,
    color: "text-cyan-400",
    bg: "bg-cyan-500/8",
    border: "border-cyan-500/20",
    badge: "bg-cyan-500/15 text-cyan-400 border-cyan-500/20",
    description: "Warden appeals to 8th Ledger. Vote required.",
  },
  ledger_update: {
    label: "8th Ledger Update",
    prefix: "[8TH LEDGER]",
    icon: Landmark,
    color: "text-violet-400",
    bg: "bg-violet-500/8",
    border: "border-violet-500/20",
    badge: "bg-violet-500/15 text-violet-400 border-violet-500/20",
    description: "Auto-generated by the 8th Ledger.",
  },
};

//  Helpers

function formatTimeAgo(date: Date): string {
  const seconds = Math.floor((Date.now() - date.getTime()) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function getVotePercent(
  yes: number,
  no: number,
  abstain: number,
): { yes: number; no: number } {
  const total = yes + no + abstain;
  if (total === 0) return { yes: 0, no: 0 };
  return {
    yes: Math.round((yes / total) * 100),
    no: Math.round((no / total) * 100),
  };
}

//  Sub-Components ─

function VoteBar({
  yes,
  no,
  abstain,
}: {
  yes: number;
  no: number;
  abstain: number;
}) {
  const { yes: yesPct, no: noPct } = getVotePercent(yes, no, abstain);
  const abstainPct = 100 - yesPct - noPct;

  return (
    <div className="mt-3 space-y-2">
      <div className="flex h-2 w-full overflow-hidden rounded-full bg-slate-800">
        {yesPct > 0 && (
          <div
            className="h-full bg-emerald-500 transition-all duration-500"
            style={{ width: `${yesPct}%` }}
          />
        )}
        {noPct > 0 && (
          <div
            className="h-full bg-red-500 transition-all duration-500"
            style={{ width: `${noPct}%` }}
          />
        )}
        {abstainPct > 0 && (
          <div
            className="h-full bg-slate-500 transition-all duration-500"
            style={{ width: `${abstainPct}%` }}
          />
        )}
      </div>
      <div className="flex items-center justify-between text-[10px] text-slate-400">
        <span className="flex items-center gap-1 text-emerald-400">
          <CheckCircle2 className="h-3 w-3" /> {yesPct}% Yes ({yes})
        </span>
        <span className="flex items-center gap-1 text-red-400">
          <XCircle className="h-3 w-3" /> {noPct}% No ({no})
        </span>
        <span className="flex items-center gap-1 text-slate-400">
          <MoreHorizontal className="h-3 w-3" /> {abstainPct}% Abstain (
          {abstain})
        </span>
      </div>
    </div>
  );
}

function StatusBadge({ status }: { status: StreamPost["status"] }) {
  if (!status) return null;
  const map: Record<
    string,
    { label: string; class: string; icon: React.ElementType }
  > = {
    active: {
      label: "Voting",
      class: "bg-amber-500/15 text-amber-400 border-amber-500/20",
      icon: Clock,
    },
    passed: {
      label: "Passed",
      class: "bg-emerald-500/15 text-emerald-400 border-emerald-500/20",
      icon: CheckCircle2,
    },
    rejected: {
      label: "Rejected",
      class: "bg-red-500/15 text-red-400 border-red-500/20",
      icon: XCircle,
    },
    executing: {
      label: "Executing",
      class: "bg-cyan-500/15 text-cyan-400 border-cyan-500/20",
      icon: Wrench,
    },
    completed: {
      label: "Completed",
      class: "bg-violet-500/15 text-violet-400 border-violet-500/20",
      icon: BadgeCheck,
    },
  };
  const cfg = map[status];
  if (!cfg) return null;
  const Icon = cfg.icon;
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider",
        cfg.class,
      )}
    >
      <Icon className="h-3 w-3" />
      {cfg.label}
    </span>
  );
}

//  Main Component ─

export function SovereignStream({
  hallId,
  hallName,
  posts,
  currentUserLedgerId,
  isSpeaker,
  isTreasurer,
  isWarden,
  isScribe,
  isAdmin,
  onCreatePost,
  onReply,
  onVote,
  onPin,
  className,
}: SovereignStreamProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [filterType, setFilterType] = useState<StreamPostType | "all">("all");
  const [expandedPostId, setExpandedPostId] = useState<string | null>(null);
  const [replyingTo, setReplyingTo] = useState<string | null>(null);
  const [replyText, setReplyText] = useState("");
  const [showComposer, setShowComposer] = useState(false);
  const [composerType, setComposerType] = useState<StreamPostType>("proposal");
  const [composerTitle, setComposerTitle] = useState("");
  const [composerContent, setComposerContent] = useState("");
  const [composerAmount, setComposerAmount] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const canCreate = isSpeaker || isTreasurer || isWarden || isScribe || isAdmin;

  const filteredPosts = useMemo(() => {
    let result = [...posts];
    if (filterType !== "all") {
      result = result.filter((p) => p.type === filterType);
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(
        (p) =>
          p.title.toLowerCase().includes(q) ||
          p.content.toLowerCase().includes(q) ||
          p.ledgerId.toLowerCase().includes(q),
      );
    }
    // Pinned first, then by date desc
    return result.sort((a, b) => {
      if (a.isPinned && !b.isPinned) return -1;
      if (!a.isPinned && b.isPinned) return 1;
      return b.createdAt.getTime() - a.createdAt.getTime();
    });
  }, [posts, filterType, searchQuery]);

  const handleCreatePost = async () => {
    if (!onCreatePost || !composerTitle.trim() || !composerContent.trim())
      return;
    setIsSubmitting(true);
    try {
      await onCreatePost({
        type: composerType,
        title: composerTitle.trim(),
        content: composerContent.trim(),
        ledgerId: currentUserLedgerId,
        amount: composerAmount ? parseFloat(composerAmount) : undefined,
        status:
          composerType === "proposal" || composerType === "appeal"
            ? "active"
            : undefined,
      });
      setComposerTitle("");
      setComposerContent("");
      setComposerAmount("");
      setShowComposer(false);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReply = async (postId: string) => {
    if (!onReply || !replyText.trim()) return;
    setIsSubmitting(true);
    try {
      await onReply(postId, replyText.trim());
      setReplyText("");
      setReplyingTo(null);
    } finally {
      setIsSubmitting(false);
    }
  };

  const toggleExpand = (id: string) => {
    setExpandedPostId((prev) => (prev === id ? null : id));
  };

  return (
    <div
      className={cn(
        "flex flex-col h-full bg-slate-950 rounded-2xl border border-slate-800 overflow-hidden",
        className,
      )}
    >
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 bg-slate-900/50 px-5 py-4">
        <div>
          <h2 className="text-sm font-bold tracking-wide text-slate-100 flex items-center gap-2">
            <MessageSquare className="h-4 w-4 text-cyan-400" />
            Sovereign Stream
          </h2>
          <p className="text-[11px] text-slate-500 mt-0.5">
            {hallName} — Structured governance. No off-topic. Immutable.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1.5 rounded-lg bg-slate-800/60 px-2.5 py-1.5 border border-slate-700/50">
            <Lock className="h-3 w-3 text-slate-400" />
            <span className="text-[10px] font-medium text-slate-400">
              Owners Only
            </span>
          </div>
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex flex-col gap-3 border-b border-slate-800 bg-slate-900/30 px-5 py-3">
        <div className="flex items-center gap-3">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-500" />
            <input
              type="text"
              placeholder="Search proposals, reports, appeals..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full rounded-xl bg-slate-800/60 border border-slate-700/50 pl-9 pr-4 py-2 text-xs text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/40 focus:ring-1 focus:ring-cyan-500/20 transition-all"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            )}
          </div>
          {canCreate && (
            <button
              onClick={() => setShowComposer((s) => !s)}
              className={cn(
                "shrink-0 rounded-xl px-4 py-2 text-xs font-semibold transition-all",
                showComposer
                  ? "bg-slate-700 text-slate-200"
                  : "bg-cyan-500/15 text-cyan-400 border border-cyan-500/30 hover:bg-cyan-500/25",
              )}
            >
              {showComposer ? "Cancel" : "New Post"}
            </button>
          )}
        </div>

        {/* Filter pills */}
        <div className="flex items-center gap-2 overflow-x-auto pb-0.5">
          <Filter className="h-3 w-3 text-slate-500 shrink-0" />
          {(
            ["all", "proposal", "report", "appeal", "ledger_update"] as const
          ).map((t) => (
            <button
              key={t}
              onClick={() => setFilterType(t)}
              className={cn(
                "shrink-0 rounded-lg px-2.5 py-1 text-[11px] font-medium transition-all border",
                filterType === t
                  ? "bg-slate-700 text-slate-100 border-slate-600"
                  : "bg-transparent text-slate-500 border-transparent hover:bg-slate-800 hover:text-slate-300",
              )}
            >
              {t === "all" ? "All Types" : TYPE_CONFIG[t].label}
            </button>
          ))}
        </div>
      </div>

      {/* Composer */}
      <AnimatePresence>
        {showComposer && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden border-b border-slate-800 bg-slate-900/40"
          >
            <div className="p-5 space-y-4">
              {/* Type selector */}
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">
                  Type
                </span>
                <div className="flex gap-2">
                  {(isSpeaker || isAdmin) && (
                    <button
                      onClick={() => setComposerType("proposal")}
                      className={cn(
                        "rounded-lg px-3 py-1.5 text-[11px] font-medium border transition-all",
                        composerType === "proposal"
                          ? "bg-amber-500/15 text-amber-400 border-amber-500/30"
                          : "bg-slate-800 text-slate-400 border-slate-700 hover:text-slate-300",
                      )}
                    >
                      Proposal
                    </button>
                  )}
                  {(isTreasurer || isAdmin) && (
                    <button
                      onClick={() => setComposerType("report")}
                      className={cn(
                        "rounded-lg px-3 py-1.5 text-[11px] font-medium border transition-all",
                        composerType === "report"
                          ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30"
                          : "bg-slate-800 text-slate-400 border-slate-700 hover:text-slate-300",
                      )}
                    >
                      Report
                    </button>
                  )}
                  {(isWarden || isAdmin) && (
                    <button
                      onClick={() => setComposerType("appeal")}
                      className={cn(
                        "rounded-lg px-3 py-1.5 text-[11px] font-medium border transition-all",
                        composerType === "appeal"
                          ? "bg-cyan-500/15 text-cyan-400 border-cyan-500/30"
                          : "bg-slate-800 text-slate-400 border-slate-700 hover:text-slate-300",
                      )}
                    >
                      Appeal
                    </button>
                  )}
                  {isAdmin && (
                    <button
                      onClick={() => setComposerType("ledger_update")}
                      className={cn(
                        "rounded-lg px-3 py-1.5 text-[11px] font-medium border transition-all",
                        composerType === "ledger_update"
                          ? "bg-violet-500/15 text-violet-400 border-violet-500/30"
                          : "bg-slate-800 text-slate-400 border-slate-700 hover:text-slate-300",
                      )}
                    >
                      8th Ledger
                    </button>
                  )}
                </div>
              </div>

              <input
                type="text"
                placeholder="Title..."
                value={composerTitle}
                onChange={(e) => setComposerTitle(e.target.value)}
                className="w-full rounded-xl bg-slate-800/60 border border-slate-700/50 px-4 py-2.5 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/40 focus:ring-1 focus:ring-cyan-500/20"
              />

              <textarea
                placeholder={`Describe your ${composerType}...`}
                value={composerContent}
                onChange={(e) => setComposerContent(e.target.value)}
                rows={4}
                className="w-full rounded-xl bg-slate-800/60 border border-slate-700/50 px-4 py-3 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/40 focus:ring-1 focus:ring-cyan-500/20 resize-none"
              />

              {(composerType === "proposal" || composerType === "appeal") && (
                <div className="flex items-center gap-3">
                  <span className="text-[11px] text-slate-400">
                    Estimated Amount ($)
                  </span>
                  <input
                    type="number"
                    placeholder="0.00"
                    value={composerAmount}
                    onChange={(e) => setComposerAmount(e.target.value)}
                    className="w-32 rounded-lg bg-slate-800/60 border border-slate-700/50 px-3 py-1.5 text-xs text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/40"
                  />
                </div>
              )}

              <div className="flex items-center justify-between">
                <p className="text-[10px] text-slate-500">
                  {TYPE_CONFIG[composerType].description}
                </p>
                <button
                  onClick={handleCreatePost}
                  disabled={
                    isSubmitting ||
                    !composerTitle.trim() ||
                    !composerContent.trim()
                  }
                  className="rounded-xl bg-cyan-500 px-5 py-2 text-xs font-semibold text-slate-950 hover:bg-cyan-400 disabled:opacity-40 disabled:cursor-not-allowed transition-colors flex items-center gap-2"
                >
                  <Send className="h-3.5 w-3.5" />
                  {isSubmitting ? "Posting..." : "Post to Stream"}
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Posts Feed */}
      <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
        {filteredPosts.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <MessageSquare className="h-10 w-10 text-slate-700 mb-3" />
            <p className="text-sm font-medium text-slate-400">
              No posts in the Sovereign Stream
            </p>
            <p className="text-[11px] text-slate-600 mt-1 max-w-xs">
              The hall is silent. Executives may initiate proposals, reports, or
              appeals.
            </p>
          </div>
        ) : (
          filteredPosts.map((post, index) => {
            const config = TYPE_CONFIG[post.type];
            const TypeIcon = config.icon;
            const isExpanded = expandedPostId === post.id;
            const canVote =
              onVote &&
              (post.type === "proposal" || post.type === "appeal") &&
              post.status === "active";
            const hasVoted = false; // Would come from user data

            return (
              <motion.div
                key={post.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05, duration: 0.3 }}
                className={cn(
                  "rounded-xl border bg-slate-900/50 overflow-hidden transition-all",
                  config.border,
                  post.isPinned && "ring-1 ring-amber-500/20",
                )}
              >
                {/* Post Header */}
                <div className="px-4 pt-4 pb-3">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-center gap-2.5">
                      <div
                        className={cn(
                          "flex h-8 w-8 items-center justify-center rounded-lg",
                          config.bg,
                        )}
                      >
                        <TypeIcon className={cn("h-4 w-4", config.color)} />
                      </div>
                      <div>
                        <div className="flex items-center gap-2 flex-wrap">
                          <span
                            className={cn(
                              "text-[10px] font-bold uppercase tracking-wider",
                              config.color,
                            )}
                          >
                            {config.prefix}
                          </span>
                          {post.isPinned && (
                            <span className="flex items-center gap-1 rounded bg-amber-500/15 px-1.5 py-0.5 text-[9px] font-semibold text-amber-400 border border-amber-500/20">
                              <Pin className="h-2.5 w-2.5" />
                              Pinned
                            </span>
                          )}
                          <StatusBadge status={post.status} />
                        </div>
                        <h3 className="text-sm font-semibold text-slate-100 mt-0.5 leading-snug">
                          {post.title}
                        </h3>
                      </div>
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      {onPin && isAdmin && (
                        <button
                          onClick={() => onPin(post.id)}
                          className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-800 hover:text-amber-400 transition-colors"
                          title={post.isPinned ? "Unpin" : "Pin"}
                        >
                          <Pin
                            className={cn(
                              "h-3.5 w-3.5",
                              post.isPinned && "fill-amber-400 text-amber-400",
                            )}
                          />
                        </button>
                      )}
                      <button
                        onClick={() => toggleExpand(post.id)}
                        className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-800 hover:text-slate-200 transition-colors"
                      >
                        {isExpanded ? (
                          <ChevronUp className="h-4 w-4" />
                        ) : (
                          <ChevronDown className="h-4 w-4" />
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Meta */}
                  <div className="mt-2 flex items-center gap-3 text-[11px] text-slate-500">
                    <span className="flex items-center gap-1">
                      <Hash className="h-3 w-3" />
                      {post.ledgerId}
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {formatTimeAgo(post.createdAt)}
                    </span>
                    {post.amount !== undefined && (
                      <>
                        <span>•</span>
                        <span className="flex items-center gap-1 text-slate-300">
                          <TrendingUp className="h-3 w-3" />$
                          {post.amount.toLocaleString()}
                        </span>
                      </>
                    )}
                    {post.voteClosesAt && (
                      <>
                        <span>•</span>
                        <span className="flex items-center gap-1 text-amber-400">
                          <Calendar className="h-3 w-3" />
                          Closes {formatTimeAgo(post.voteClosesAt)}
                        </span>
                      </>
                    )}
                  </div>
                </div>

                {/* Content */}
                <div className="px-4 pb-3">
                  <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-wrap">
                    {post.content}
                  </p>
                </div>

                {/* Vote Section */}
                {canVote &&
                  post.voteYes !== undefined &&
                  post.voteNo !== undefined &&
                  post.voteAbstain !== undefined && (
                    <div className="px-4 pb-3">
                      <VoteBar
                        yes={post.voteYes}
                        no={post.voteNo}
                        abstain={post.voteAbstain}
                      />
                      {!hasVoted && (
                        <div className="mt-3 flex items-center gap-2">
                          <button
                            onClick={() => onVote?.(post.id, "yes")}
                            className="flex-1 rounded-lg bg-emerald-500/10 py-2 text-xs font-semibold text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/20 transition-colors flex items-center justify-center gap-1.5"
                          >
                            <CheckCircle2 className="h-3.5 w-3.5" />
                            Yes
                          </button>
                          <button
                            onClick={() => onVote?.(post.id, "no")}
                            className="flex-1 rounded-lg bg-red-500/10 py-2 text-xs font-semibold text-red-400 border border-red-500/20 hover:bg-red-500/20 transition-colors flex items-center justify-center gap-1.5"
                          >
                            <XCircle className="h-3.5 w-3.5" />
                            No
                          </button>
                          <button
                            onClick={() => onVote?.(post.id, "abstain")}
                            className="flex-1 rounded-lg bg-slate-700/50 py-2 text-xs font-semibold text-slate-400 border border-slate-600/30 hover:bg-slate-700 transition-colors flex items-center justify-center gap-1.5"
                          >
                            <MoreHorizontal className="h-3.5 w-3.5" />
                            Abstain
                          </button>
                        </div>
                      )}
                    </div>
                  )}

                {/* Replies Preview */}
                {post.replies.length > 0 && !isExpanded && (
                  <div className="px-4 pb-3">
                    <button
                      onClick={() => toggleExpand(post.id)}
                      className="flex items-center gap-2 text-[11px] text-slate-500 hover:text-cyan-400 transition-colors"
                    >
                      <Reply className="h-3.5 w-3.5" />
                      {post.replies.length}{" "}
                      {post.replies.length === 1 ? "reply" : "replies"} — click
                      to view
                    </button>
                  </div>
                )}

                {/* Expanded: Replies + Reply Form */}
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.2 }}
                      className="overflow-hidden border-t border-slate-800/60"
                    >
                      <div className="px-4 py-3 space-y-3">
                        {post.replies.length === 0 ? (
                          <p className="text-[11px] text-slate-600 italic">
                            No replies yet.
                          </p>
                        ) : (
                          post.replies.map((reply) => (
                            <div
                              key={reply.id}
                              className="flex gap-3 rounded-lg bg-slate-800/40 p-3 border border-slate-800/50"
                            >
                              <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-slate-700 text-slate-300">
                                {reply.avatar ? (
                                  <img
                                    src={reply.avatar}
                                    alt=""
                                    className="h-full w-full rounded-full object-cover"
                                  />
                                ) : (
                                  <span className="text-[10px] font-bold">
                                    {(reply.displayName || reply.ledgerId)
                                      .charAt(0)
                                      .toUpperCase()}
                                  </span>
                                )}
                              </div>
                              <div className="min-w-0 flex-1">
                                <div className="flex items-center gap-2 flex-wrap">
                                  <span className="text-xs font-semibold text-slate-200">
                                    {reply.displayName || reply.ledgerId}
                                  </span>
                                  {reply.isExecutive && (
                                    <span className="rounded bg-cyan-500/15 px-1.5 py-0.5 text-[9px] font-semibold text-cyan-400 border border-cyan-500/20">
                                      {reply.executiveRole}
                                    </span>
                                  )}
                                  <span className="text-[10px] text-slate-500">
                                    {formatTimeAgo(reply.createdAt)}
                                  </span>
                                </div>
                                <p className="text-xs text-slate-300 mt-1 leading-relaxed">
                                  {reply.content}
                                </p>
                              </div>
                            </div>
                          ))
                        )}

                        {/* Reply Input */}
                        {replyingTo === post.id ? (
                          <div className="flex gap-2">
                            <input
                              type="text"
                              placeholder="Write a threaded reply..."
                              value={replyText}
                              onChange={(e) => setReplyText(e.target.value)}
                              onKeyDown={(e) =>
                                e.key === "Enter" &&
                                !e.shiftKey &&
                                handleReply(post.id)
                              }
                              className="flex-1 rounded-lg bg-slate-800/60 border border-slate-700/50 px-3 py-2 text-xs text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/40"
                              autoFocus
                            />
                            <button
                              onClick={() => handleReply(post.id)}
                              disabled={isSubmitting || !replyText.trim()}
                              className="rounded-lg bg-cyan-500/15 px-3 py-2 text-cyan-400 border border-cyan-500/30 hover:bg-cyan-500/25 disabled:opacity-40 transition-colors"
                            >
                              <Send className="h-3.5 w-3.5" />
                            </button>
                            <button
                              onClick={() => {
                                setReplyingTo(null);
                                setReplyText("");
                              }}
                              className="rounded-lg bg-slate-800 px-3 py-2 text-slate-400 hover:text-slate-200 transition-colors"
                            >
                              <X className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        ) : (
                          <button
                            onClick={() => setReplyingTo(post.id)}
                            className="flex items-center gap-2 text-[11px] text-slate-500 hover:text-cyan-400 transition-colors"
                          >
                            <Reply className="h-3.5 w-3.5" />
                            Reply to this thread
                          </button>
                        )}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })
        )}
      </div>
    </div>
  );
}

//  Skeleton ─

export function SovereignStreamSkeleton() {
  return (
    <div className="flex flex-col h-full bg-slate-950 rounded-2xl border border-slate-800 overflow-hidden">
      <div className="border-b border-slate-800 bg-slate-900/50 px-5 py-4">
        <div className="h-4 w-40 rounded bg-slate-800 animate-pulse" />
        <div className="h-3 w-64 rounded bg-slate-800 animate-pulse mt-2" />
      </div>
      <div className="px-5 py-3 space-y-3">
        <div className="h-9 rounded-xl bg-slate-800 animate-pulse" />
        <div className="flex gap-2">
          {[1, 2, 3, 4, 5].map((i) => (
            <div
              key={i}
              className="h-6 w-20 rounded-lg bg-slate-800 animate-pulse"
            />
          ))}
        </div>
      </div>
      <div className="flex-1 px-5 py-4 space-y-4">
        {[1, 2, 3].map((i) => (
          <div
            key={i}
            className="rounded-xl border border-slate-800 bg-slate-900/50 p-4 space-y-3"
          >
            <div className="flex items-start gap-3">
              <div className="h-8 w-8 rounded-lg bg-slate-800 animate-pulse" />
              <div className="flex-1 space-y-2">
                <div className="h-3 w-24 rounded bg-slate-800 animate-pulse" />
                <div className="h-4 w-3/4 rounded bg-slate-800 animate-pulse" />
              </div>
            </div>
            <div className="h-16 rounded bg-slate-800 animate-pulse" />
          </div>
        ))}
      </div>
    </div>
  );
}

export default SovereignStream;
